config/routes.rb
Rails.application.routes.draw do
  resources :coursesubjects
  resources :enrollments
  get 'admin/index'

	get 'users/index'	
	
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'
  
  post 'sessions/new' => 'sessions#create'
  
  controller :sessions do
  	get 'login' => :new
  	post 'login' => :create
  	delete 'logout' => :destroy
  end

  resources :instructors
  resources :subjects
  resources :courses
  resources :users
  
  root 'sessions#new'

end

app/models/user.rb
class User < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true
	has_secure_password
	
	has_many :enrollments
	has_many :courses, through: :enrollments

	def self.current_user
		Thread.current[:current_user]
	end
	
	def self.current_user=(usr)
		Thread.current[:current_user] = usr
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_filter :authorize, only: [:create, :new]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url, notice: "User #{@user.name} was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <fieldset>
  <legend>Enter User Details</legend>
		<div class="field">
	    <%= f.label :name %><br>
	    <%= f.text_field :name %>
	  </div>
	  <div class="field">
	    <%= f.label :password, 'Password' %><br>
	    <%= f.password_field :password %>
	  </div>
	  <div class="field">
	    <%= f.label :password_confirmation, 'Confirm' %><br>
	    <%= f.password_field :password_confirmation %>
	  </div>
	  <div class="actions">
	    <%= f.submit %>
	  </div>
	</fieldset>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%= link_to 'Users' , users_path %>
<%= link_to 'Subjects', subjects_path %>
<%= link_to 'Courses', courses_path %>
<%= link_to 'Instructors', instructors_path %>
<%= link_to 'Search', enrollments_path %>
<%= link_to 'Log Out', sessions_destroy_url %>

<h1>Listing users</h1>
	<% if notice %>
	<p id="notice"><%= notice %></p>
	<% end %>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  	<tr>
  		<td> <%= User.current_user.name %></td>
  		<td> <%= link_to 'Currently Enrolled Courses', User.current_user %></td>
  	</tr>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back to login', root_url %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>