config/routes.rb
Rails.application.routes.draw do
  resources :coursesubjects
  resources :enrollments
  get 'admin/index'

	get 'users/index'	
	
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'
  
  post 'sessions/new' => 'sessions#create'
  
  controller :sessions do
  	get 'login' => :new
  	post 'login' => :create
  	delete 'logout' => :destroy
  end

  resources :instructors
  resources :subjects
  resources :courses
  resources :users
  
  root 'sessions#new'

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
	belongs_to :user
	belongs_to :course
	
	def Course.search(search)
		where("name LIKE ?", "%#{search}%")
	end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
	before_filter :authorize
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]

  # GET /enrollments
  # GET /enrollments.json
  def index
    @enrollments = Enrollment.all
    if params[:search]
    	@courses = Course.search(params[:search]).order("created_at DESC")
    else
    	@courses = Course.all.order('created_at DESC')
    end
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully created.' }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1
  # PATCH/PUT /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrollment_params
      params.fetch(:enrollment, {})
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_form.html.erb
<%= form_for(@enrollment) do |f| %>
  <% if @enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
      <% @enrollment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing enrollment</h1>

<%= render 'form' %>

<%= link_to 'Show', @enrollment %> |
<%= link_to 'Back', enrollments_path %>

app/views/enrollments/index.html.erb
<%= link_to 'Users' , users_path %>
<%= link_to 'Subjects', subjects_path %>
<%= link_to 'Courses', courses_path %>
<%= link_to 'Instructors', instructors_path %>
<%= link_to 'Search', enrollments_path %>
<%= link_to 'Log Out', sessions_destroy_url %>


<h1>Search for a course</h1>
<p>You can search by course, subject, or both</p>

<%= form_tag(courses_path, :method => "get", id: "search-form") do %>
	<%= text_field_tag :search, params[:search], placeholder: "Search Courses" %>
	<%= submit_tag "Search", :name => nil %>
<% end %>

<p>
	<%= @courses %>
</p>

app/views/enrollments/new.html.erb
<h1>New enrollment</h1>

<%= render 'form' %>

<%= link_to 'Back', enrollments_path %>

app/views/enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_enrollment_path(@enrollment) %> |
<%= link_to 'Back', enrollments_path %>